#!/bin/sh

if cmd_exists thunar; then
  function open() {
     local open_path=${1:-.}
     thunar ${open_path}
  }
elif cmd_exists finder; then 
     :  "mac no settings."
elif cmd_exists explorer; then
   : "windows no settings."
else
     echo "warning: file manager is not setting."
fi 