#!/bin/sh

if ! cmd_exists peco; then
  :
else
peco-select-history() {
    local tac
    if which tac > /dev/null; then
        tac="tac"
    else
        tac="tail -r"
    fi
    BUFFER=$(\history -n 1 | \
        eval $tac | \
        peco --layout=bottom-up --query "$LBUFFER")
    CURSOR=$#BUFFER
} && zle -N peco-select-history

peco-git-recent-branches () {
    local selected_branch=$(git for-each-ref --format='%(refname)' --sort=-committerdate refs/heads | \
        perl -pne 's{^refs/heads/}{}' | \
        peco --layout=bottom-up)
    if [ -n "$selected_branch" ]; then
        BUFFER="git checkout ${selected_branch}"
        zle accept-line
    fi
} && zle -N peco-git-recent-branches

peco-find-file() {
  if git rev-parse 2> /dev/null; then
    source_files=$(git ls-files)
  else	
    source_files=$(find . -type f)
  fi
  selected_files=$(echo $source_files | peco --prompt "[find file]" --layout=bottom-up)
	BUFFER="${BUFFER}$(echo $selected_files | tr '\n' ' ')"
	CURSOR=$#BUFFER
} && zle -N peco-find-file

peco-snippets() {
	if [ ! -e $snippets_file_path ]; then
		touch $snippets_file_path
	fi
	BUFFER=$(grep -v "^#" $snippets_file_path | peco --query "$LBUFFER" --prompt "[find snippets.]" --layout=bottom-up )
	CURSOR=$#BUFFER
	zle clear-screen
} && zle -N peco-snippets

peco-snippets-add() {
	if [ ! -e $snippets_file_path ]; then
		touch $snippets_file_path
	fi
	echo $BUFFER >> $snippets_file_path
	zle -M "snippets entry! $BUFFER"
} && zle -N peco-snippets-add

peco-find-docker-ps() {
  selected_id=$(docker ps | tail -n +2 | peco --prompt "[find process]" --layout=bottom-up | cut -d" " -f1)
  BUFFER="${BUFFER}$(echo $selected_id | tr '\n' ' ')"
  CURSOR=$#BUFFER
} && zle -N peco-find-docker-ps
fi
