#!/bin/bash

: "I/O functions" && {
  message() {
    echo "$@" 1>&2
  }
  abort() { 
    echo "$@" 1>&2
    exit 1
  }
}
: "file/dir functions" && {
  current_dir() {
     echo $(cd $(dirname $0); pwd)
  }
}
: "string functions" && {
  win2nxp() {
		printf %q "$1" | sed -e 's/\\\\/\//g'
	}
}

: "general functions" && {
  find_process() {
    ps aux | grep $1 | grep -v grep
  }

  get_os_type() {
    uname -a | grep "microsoft" | grep "Linux">/dev/null
    local res=$? 
    if [ $res -eq 0 ]; then
      echo 'Windows_Linux'
    else 
      echo `uname`
    fi
  }

  is_linux_os() {
    [[ "Linux" = `get_os_type` ]]
  }
}

: "alias settings" && {
  if cmd_exists lsd; then
    alias ll='lsd -al'
  elif cmd_exists exa; then
    alias ll='exa -al'
  else
    alias ll='ls -al'
  fi
}
